--1
SELECT CLIENTE.CD_CLIENTE, CLIENTE.NM_CLIENTE, CLIENTEENDERECO.DS_ENDERECO, CLIENTEENDERECO.NR_ENDERECO AS NR_NUMERO,
       CLIENTEENDERECO.NR_CEP, BAIRRO.NM_BAIRRO, MUNICIPIO.DS_MUNICIPIO, ESTADO.SG_ESTADO
FROM CLIENTE
    LEFT JOIN CLIENTEENDERECO ON CLIENTE.CD_CLIENTE = CLIENTEENDERECO.CD_CLIENTE
    LEFT JOIN BAIRRO ON CLIENTEENDERECO.CD_BAIRRO = BAIRRO.CD_BAIRRO
    LEFT JOIN MUNICIPIO ON CLIENTEENDERECO.CD_MUNICIPIO = MUNICIPIO.CD_MUNICIPIO
    LEFT JOIN ESTADO ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO
ORDER BY CLIENTE.CD_CLIENTE

--2
SELECT ESTADO.SG_ESTADO, COUNT(DISTINCT(CLIENTEENDERECO.CD_CLIENTE)) AS QUANTIDADE
FROM ESTADO
    LEFT JOIN MUNICIPIO ON ESTADO.CD_ESTADO = MUNICIPIO.CD_ESTADO
    LEFT JOIN CLIENTEENDERECO ON MUNICIPIO.CD_MUNICIPIO = CLIENTEENDERECO.CD_MUNICIPIO
GROUP BY ESTADO.SG_ESTADO

--3 CASO APRESENTE ERRO NOS CAMPOS VL_TOTAL, SUBSTIRUIR AS ASPAS DUPLAS POR SIMPLES
SELECT NOTA.CD_NOTA, NOTA.VL_TOTAL AS "VL_TOTAL (NOTA)", NOTAITEM.CD_NOTAITEM, PRODUTO.CD_PRODUTO,
       PRODUTO.NM_PRODUTO, NOTAITEM.NR_QUANTIDADE, NOTAITEM.VL_UNITARIO,
       NOTAITEM.VL_TOTAL AS "VL_TOTAL (ITEM)"
FROM NOTAITEM
    INNER JOIN NOTA ON NOTAITEM.CD_NOTA = NOTA.CD_NOTA
    INNER JOIN PRODUTO ON NOTAITEM.CD_PRODUTO = PRODUTO.CD_PRODUTO
ORDER BY NOTAITEM.VL_TOTAL DESC

--4 CASO APRESENTE ERRO NOS CAMPOS DT_VENCIMENTO, SUBSTIRUIR AS ASPAS DUPLAS POR SIMPLES, FOI USADO O CAST PARA VARCHAR POIS O ANO ESTAVA SENDO APRESENTADO COM , NA MINHA CONSULTA
SELECT CLIENTE.CD_CLIENTE,
       CAST(EXTRACT(MONTH FROM NOTAFIN.DT_VENCIMENTO) AS VARCHAR(2)) AS "DT_VENCIMENTO (MÊS)",
       CAST(EXTRACT(YEAR FROM NOTAFIN.DT_VENCIMENTO) AS VARCHAR(4)) AS "DT_VENCIMENTO (ANO)",
       NOTAFIN.VL_PARCELA AS "VL_PARCELA (TOTAL NO MÊS E ANO)"
FROM NOTA
    LEFT JOIN NOTAFIN ON NOTA.CD_NOTA = NOTAFIN.CD_NOTA
    LEFT JOIN CLIENTE ON NOTA.CD_CLIENTE = CLIENTE.CD_CLIENTE
ORDER BY CLIENTE.CD_CLIENTE

--5 CASO APRESENTE ERRO NOS CAMPOS VL_TOTAL, SUBSTIRUIR AS ASPAS DUPLAS POR SIMPLES, FOI USADO O CAST PARA VARCHAR POIS O ANO ESTAVA SENDO APRESENTADO COM , NA MINHA CONSULTA
SELECT FIRST 1 SG_ESTADO, VL_TOTAL AS "VALOR TOTAL VENDAS"
FROM (SELECT ESTADO.SG_ESTADO, SUM(NOTA.VL_TOTAL) AS "VL_TOTAL"
      FROM NOTA
          LEFT JOIN CLIENTEENDERECO ON NOTA.CD_CLIENTE = CLIENTEENDERECO.CD_CLIENTE
          LEFT JOIN MUNICIPIO ON CLIENTEENDERECO.CD_MUNICIPIO = MUNICIPIO.CD_MUNICIPIO
          LEFT JOIN ESTADO ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO
      GROUP BY ESTADO.SG_ESTADO)
ORDER BY VL_TOTAL DESC      
